apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace-server
  template:
    metadata:
      labels:
        app: ace-server
    spec:
      containers:
      - name: ace
        image: prahladpal/ace13:v1
        ports:
        - containerPort: 4414
        - containerPort: 7080
        - containerPort: 7800
        env:
        - name: LICENSE
          value: accept
        - name: ACE_SERVER_NAME
          value: default
        volumeMounts:
        - name: bar-volume
          mountPath: /home/aceuser/initial-config/bars
      volumes:
      - name: bar-volume
        configMap:
         name: ace-bar-config
