apiVersion: v1
kind: ConfigMap
metadata:
 name: ns-configmap
 namespace: my-4thdaypractice-ns
data:
 index.html: |
  <html>
   <body>
      <h1>test for k8 namespace using ConfigMap</h1>
   </body>
  </html>