apiVersion: v1
kind: Service
metadata:
 name: my-ns-service
 namespace: my-4thdaypractice-ns
spec:
 type: NodePort
 selector:
  app: my-nspod-n1
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30017