apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-nspod-deployment
spec:
 replicas: 3
 selector:
  matchLabels:
   app: my-nspod
   namespace: my-4thdaypractice-ns
 template:
  metadata:
   labels:
    app: my-nspod
    namespace: my-4thdaypractice-ns
  spec:
   containers:
   - name: fourth-container
     image: prahladpal/k8-cluster-html:1.0
     ports:
     - containerPort: 80
